'use strict';
function handleClick(event){ const btn=event.target.closest('button,[data-action],[data-focus],[data-muscle],[data-exercise-option],[data-start-routine],[data-analysis-tab]');if(!btn)return;
  if(btn.dataset.route){navigate(btn.dataset.route);return;} if(btn.dataset.closeModal!==undefined||btn.dataset.action==='close-modal'){closeModal();return;}
  if(btn.dataset.focus){builder.focus=btn.dataset.focus;builder.muscle=null;builder.selected=[];render();return;} if(btn.dataset.muscle){builder.muscle=btn.dataset.muscle;render();return;}
  if(btn.dataset.exerciseOption){ if(btn.dataset.customExercise){const name=prompt('Nombre del ejercicio');if(name){const ex={name,icon:'✍️',region:builder.focus==='lower'?'lower':'upper',primary:builder.muscle,secondary:[],equipment:'Personalizado',rep:[8,15],rest:120,increment:2.5};state.customExercises.push(ex);builder.selected.push(name);saveState();}}else{const name=btn.dataset.exerciseOption;builder.selected=builder.selected.includes(name)?builder.selected.filter(n=>n!==name):[...builder.selected,name];}render();return;}
  if(btn.dataset.startRoutine){startRoutine(btn.dataset.startRoutine);return;} if(btn.dataset.analysisTab){analysisTab=btn.dataset.analysisTab;render();return;}
  const action=btn.dataset.action; if(!action)return;
  if(action==='go-workout')navigate('workout'); else if(action==='go-analysis'){analysisTab='volume';navigate('analytics');} else if(action==='recovery-check')openRecoveryCheck(); else if(action==='save-recovery')saveRecovery(); else if(action==='start-builder')startBuilderSession(); else if(action==='clear-builder'){builder={focus:null,muscle:null,selected:[]};render();} else if(action==='save-builder-routine'){routineDraft={id:uid('routine'),name:`${builder.focus==='lower'?'Lower':'Upper'} personalizada`,focus:builder.focus,builtin:false,exercises:builder.selected.map(n=>planFromExercise(libraryExercise(n)))};openRoutineEditor(routineDraft);} else if(action==='finish-workout')finishWorkout(); else if(action==='cancel-workout')cancelWorkout(); else if(action==='open-active-picker')openExercisePicker('active','free');
  else if(action==='complete-set'||action==='complete-warmup')completeSet(btn.closest('.exercise-card'),action==='complete-warmup'); else if(action==='substitute-exercise'){const card=btn.closest('.exercise-card'),i=num(card.dataset.exerciseIndex),muscle=state.activeSession.exercises[i].primaryMuscle;openExercisePicker(`replace:${i}`,MUSCLE_GROUPS.lower.includes(muscle)?'lower':MUSCLE_GROUPS.upper.includes(muscle)?'upper':'free');} else if(action==='remove-set'){const card=btn.closest('.exercise-card'),i=num(card.dataset.exerciseIndex),si=num(btn.dataset.setIndex);state.activeSession.exercises[i].sets.splice(si,1);saveState();render();} else if(action==='remove-exercise'){const card=btn.closest('.exercise-card'),i=num(card.dataset.exerciseIndex);if(confirm('¿Eliminar ejercicio y sus series?')){state.activeSession.exercises.splice(i,1);saveState();render();}} else if(action==='move-exercise-up'){const card=btn.closest('.exercise-card'),i=num(card.dataset.exerciseIndex);if(i>0){[state.activeSession.exercises[i-1],state.activeSession.exercises[i]]=[state.activeSession.exercises[i],state.activeSession.exercises[i-1]];saveState();render();}} else if(action==='plate-calculator'){plateCalculator(btn.closest('.exercise-card').querySelector('.quick-weight').value);}
  else if(action==='new-routine')openRoutineEditor(); else if(action==='edit-routine')openRoutineEditor(state.routines.find(r=>r.id===btn.dataset.id)); else if(action==='delete-routine'){if(confirm('¿Eliminar rutina?')){state.routines=state.routines.filter(r=>r.id!==btn.dataset.id);saveState();render();}} else if(action==='routine-add-exercise')openExercisePicker('routine',routineDraft.focus); else if(action==='routine-remove-plan'){routineDraft.exercises.splice(num(btn.dataset.index),1);refreshRoutineDraft();} else if(action==='save-routine')saveRoutine(); else if(action==='new-mesocycle')openMesocycleEditor(); else if(action==='save-mesocycle'){const ids=qsa('input[name="mesoRoutine"]:checked',modalRoot).map(x=>x.value);if(!ids.length){showToast('Selecciona una rutina');return;}const m={id:uid('meso'),name:$('mesoName').value.trim()||'Mesociclo',weeks:num($('mesoWeeks').value,4),currentWeek:1,routineIds:ids,startedAt:dateKey(),completed:false};state.mesocycles.push(m);state.activeMesocycleId=m.id;saveState();closeModal();render();} else if(action==='advance-mesocycle'){const m=state.mesocycles.find(x=>x.id===btn.dataset.id);if(m)m.currentWeek=Math.min(m.weeks,m.currentWeek+1);saveState();render();} else if(action==='end-mesocycle'){const m=state.mesocycles.find(x=>x.id===btn.dataset.id);if(m)m.completed=true;state.activeMesocycleId=null;saveState();render();}
  else if(action==='save-profile'){state.profile.name=$('profileName').value.trim();state.profile.weight=$('profileWeight').value;state.profile.height=$('profileHeight').value;state.profile.waterGoal=$('profileWaterGoal').value;saveState();showToast('Perfil guardado');} else if(action==='save-settings'){state.settings.restTargetSeconds=num($('settingRest').value,180);state.settings.barWeight=num($('settingBar').value,20);state.settings.autoRest=$('settingAutoRest').value==='1';state.settings.wakeLock=$('settingWake').value==='1';saveState();showToast('Preferencias guardadas');} else if(action==='save-targets'){qsa('[data-target-min]').forEach(x=>state.muscleTargets[x.dataset.targetMin].min=num(x.value));qsa('[data-target-max]').forEach(x=>state.muscleTargets[x.dataset.targetMax].max=num(x.value));saveState();showToast('Objetivos guardados');} else if(action==='save-measurement'){state.measurements.push({id:uid('measure'),date:$('measureDate').value||dateKey(),weight:$('measureWeight').value,waist:$('measureWaist').value,chest:$('measureChest').value,arm:$('measureArm').value,thigh:$('measureThigh').value});saveState();render();showToast('Medición guardada');}
  else if(action==='export-json')exportJson(); else if(action==='export-csv')exportCsv(); else if(action==='reset-all'){if(confirm('Esto borrará todos los datos locales. ¿Continuar?')){state=defaultState();saveState(false);render();}} else if(action==='cloud-login')cloudAuth('login'); else if(action==='cloud-signup')cloudAuth('signup'); else if(action==='cloud-push'){cloudConfigFromForm();cloudPush();} else if(action==='cloud-pull'){cloudConfigFromForm();cloudPull();}
}
function handleModalClick(event){ const btn=event.target.closest('[data-modal-muscle],[data-picker-exercise],[data-picker-custom]');if(!btn)return;if(btn.dataset.modalMuscle){openPickerContent(btn.dataset.pickerTarget,btn.dataset.pickerFocus,btn.dataset.modalMuscle);return;}const target=btn.dataset.pickerTarget;if(btn.dataset.pickerCustom){const name=prompt('Nombre del ejercicio');if(!name)return;const ex={name,icon:'✍️',region:'custom',primary:btn.dataset.customMuscle,secondary:[],equipment:'Personalizado',rep:[8,15],rest:120,increment:2.5};state.customExercises.push(ex);saveState(false);if(target==='routine'){routineDraft.exercises.push(planFromExercise(ex));openRoutineEditor(routineDraft);}else if(target?.startsWith('replace:')){const index=num(target.split(':')[1]),current=state.activeSession?.exercises[index],plan=planFromExercise(ex);if(current){state.activeSession.exercises[index]={...current,name:plan.name,icon:plan.icon,primaryMuscle:plan.primaryMuscle,secondaryMuscles:plan.secondaryMuscles,equipment:plan.equipment,plan:{setsTarget:current.plan?.setsTarget||plan.setsTarget,repMin:plan.repMin,repMax:plan.repMax,targetRir:current.plan?.targetRir??plan.targetRir,restSeconds:plan.restSeconds,increment:plan.increment},sets:[]};saveState();closeModal();render();}}else addActiveExercise(ex);return;}const ex=libraryExercise(btn.dataset.pickerExercise);if(!ex)return;if(target==='routine'){routineDraft.exercises.push(planFromExercise(ex));openRoutineEditor(routineDraft);}else if(target?.startsWith('replace:')){const index=num(target.split(':')[1]),current=state.activeSession?.exercises[index],plan=planFromExercise(ex);if(current){state.activeSession.exercises[index]={...current,name:plan.name,icon:plan.icon,primaryMuscle:plan.primaryMuscle,secondaryMuscles:plan.secondaryMuscles,equipment:plan.equipment,plan:{setsTarget:current.plan?.setsTarget||plan.setsTarget,repMin:plan.repMin,repMax:plan.repMax,targetRir:current.plan?.targetRir??plan.targetRir,restSeconds:plan.restSeconds,increment:plan.increment},sets:[]};saveState();closeModal();render();showToast('Ejercicio sustituido');}}else addActiveExercise(ex);}
function handleInput(event){ if(event.target.matches('[data-plan-field]')&&routineDraft){routineDraft.exercises[num(event.target.dataset.index)][event.target.dataset.planField]=num(event.target.value);return;} if(event.target.id==='activeSessionName'&&state.activeSession){state.activeSession.name=event.target.value;saveState();} if(event.target.id==='sessionNotes'&&state.activeSession){state.activeSession.notes=event.target.value;saveState();} if(event.target.id==='progressExerciseSelect'){sessionStorage.setItem('progressExercise',event.target.value);render();} if(event.target.id==='historySearch'){const q=event.target.value.toLocaleLowerCase('es');qsa('[data-history-text]').forEach(el=>el.classList.toggle('hidden',!el.dataset.historyText.includes(q)));}}
function handleChange(event){if(event.target.id==='importJson'){const file=event.target.files?.[0];if(!file)return;const reader=new FileReader();reader.onload=()=>{try{state=normalizeState(JSON.parse(reader.result));saveState(false);render();showToast('Respaldo importado');}catch{showToast('Archivo inválido');}};reader.readAsText(file);} if(event.target.id==='cloudAuto'){cloudConfigFromForm();}}

window.addEventListener('hashchange',()=>{currentRoute=location.hash.replace('#/','')||'dashboard';render();});
document.addEventListener('click',handleClick);
modalRoot.addEventListener('click',event=>{if(event.target.matches('[data-close-modal]'))closeModal();else handleModalClick(event);});
document.addEventListener('input',handleInput);
document.addEventListener('change',handleChange);
document.addEventListener('click',event=>{const rir=event.target.closest('[data-rir]');if(rir){qsa('[data-rir]',rir.parentElement).forEach(b=>b.classList.remove('active'));rir.classList.add('active');}});
$('restDockPause').addEventListener('click',pauseRest);$('restDockSkip').addEventListener('click',stopRest);
window.addEventListener('beforeinstallprompt',event=>{event.preventDefault();deferredInstallPrompt=event;$('installBtn').classList.remove('hidden');});
$('installBtn').addEventListener('click',async()=>{if(!deferredInstallPrompt)return;deferredInstallPrompt.prompt();await deferredInstallPrompt.userChoice;deferredInstallPrompt=null;$('installBtn').classList.add('hidden');});
document.addEventListener('visibilitychange',()=>{if(document.visibilityState==='visible'&&state.activeSession)requestWakeLock();});

migrateV2();
if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js').catch(console.warn);
render();
if(state.activeSession)requestWakeLock();
